FROM python:3

RUN mkdir /src
WORKDIR /src

COPY api-requirements.txt .
RUN \
    pip install --no-cache-dir -r api-requirements.txt \
    && pip install --no-cache-dir uwsgi
COPY dockermirror/ /src/dockermirror

VOLUME /var/spool/dockermirror

ENTRYPOINT ["uwsgi", "--socket", "0.0.0.0:5000", "--manage-script-name", "--mount", "/=dockermirror.api:app"]
