FROM python:3

COPY api-requirements.txt .
RUN pip install --no-cache-dir -r api-requirements.txt
COPY dockermirror/ dockermirror/

VOLUME /var/spool/dockermirror

ENV FLASK_APP=dockermirror.api.app
ENTRYPOINT ["flask", "run", "--host=0.0.0.0"]
